package OpenData::BR::WWW::Model::DB;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'OpenData::BR::Schema',
    connect_info => {
        dsn => 'dbi:mysql:dbname=opendatabr_org',    
        user => 'thiago',
        password => '',
    }
);

=head1 NAME

OpenData::BR::WWW::Model::DB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<OpenData::BR::WWW>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<OpenData::BR::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.48

=head1 AUTHOR

Thiago Rondon

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
